import { Inter } from "next/font/google";
import "./globals.css";

import ThemeProviders from "@/provider/ThemeProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      data-theme="light"
      lang="en"
      suppressHydrationWarning
      className={`${inter.variable}  h-full antialiased`}
    >
      <body className="min-h-full font-inter">
        <ThemeProviders>{children}</ThemeProviders>
      </body>
    </html>
  );
}
